name: Continuous Integration

on: pull_request

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

env:
  LATEST_NODE_VERSION: 20

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [20, 22]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --prefer-offline

      # - name: Build
      #   run: pnpm build --concurrency=12

      - name: Run unit tests
        run: pnpm test:ci

      # - name: Run Vitest unit tests
      #   run: pnpm test:vitest:ci
